# Generated by Django 5.2.7 on 2025-11-17 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtechnician', '0001_initial'),
        ('receptionist', '0002_consultationbill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreport',
            name='bill_amount',
        ),
        migrations.CreateModel(
            name='LabBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='labtechnician.labbill')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labtechnician.labtestcategory')),
            ],
        ),
    ]
