# Generated by Django 5.2.7 on 2025-11-17 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
        ('labtechnician', '0002_remove_labreport_bill_amount_labbill_labbillitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='fulfill_lab_internally',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='fulfill_pharmacy_internally',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='LabTestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_orders', to='doctor.consultation')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labtechnician.labtestcategory')),
            ],
        ),
    ]
